Package
pni-lab/connattractor pull request #24
Opened 2023-11-09 16:01 UTC by englertr

tested it locally, will try to push it to PyPI when you give the green light! 

I moved everything with the timeseries to the utils (including scrubbing), so that from the outside its just a single function call

2023-11-15 08:14 UTC, spisakt requested changes
Looks good. I have a few comments.

2023-11-15 08:14 UTC, spisakt commented on pyproject.toml
> +description = "Tools for analyzing and quantifying effects of counfounder variables on machine learning model predictions."
fix deescription

2023-11-15 08:14 UTC, spisakt commented on pyproject.toml
> +PyQt5 = ">=5.15.10"
what do we need pyQt for?

2023-11-15 08:14 UTC, spisakt commented on connattractor/utils.py
> +def get_fcHNN_embedding():
reaname it to get_fcHNN_template_embedding()

2023-11-15 08:14 UTC, spisakt commented on pyproject.toml
> +    "functional connectivity analysis",
add "fcHNN", "functional connectome" and "Hopfield"

2023-11-16 12:37 UTC, englertr commented on pyproject.toml
> +PyQt5 = ">=5.15.10"
removed

2023-11-17 10:59 UTC, spisakt approved these changes
Thank you!

2023-11-17 11:00 UTC, merged